# Playbook to call multiple roles to configure systems
- name: Configure systems
  hosts: testamerico
  become: yes

  tasks:
  
- name: Call Roles
  hosts: testamerico
  roles:
   - hostname
   #- firewalld
   #- ntp-config
   #- motd
