# Playbook to call multiple roles to configure systems
- name: Configure systems
  hosts: localhost
  become: no

  tasks:

# test Americo
- name: "Hostname"
  debug:
  msg: "hostname {{ inventory_hostname }}"
  
#- name: Call Roles
#  hosts: localhost
#  roles:
#   - hostname
   #- firewalld
   #- ntp-config
   #- motd
