# Playbook to call multiple roles to configure systems
- name: Configure systems
  hosts: servers
  become: no

  tasks:
  
- name: Call Roles
  hosts: servers
  roles:
   - hostname
   #- firewalld
   #- ntp-config
   #- motd

# test Americo
#---
#  - name: "Orchestration Example"
#    hosts: servers
    
#    tasks:
    
#    - name: "Hostname"
#      debug:
#        msg: "hostname {{ inventory_hostname }}"
